module.exports = {
  dates: [
    {id: 1, date: 'July 14 2022', status_id: 12},
    {id: 2, date: 'July 15 2022', status_id: 02},
    {id: 3, date: 'July 16 2022', status_id: 03},
    {id: 4, date: 'July 17 2022', status_id: 04},
    {id: 5, date: 'July 18 2022', status_id: 05 }
  ],
  statuses: [
    {date_id: 1, title: ['Transaction 1'], type:[ 'Completed'],},
    {date_id: 1, title: ['New Transaction 1'], type:[ 'Pending'],},
    {date_id: 1, title: ['Basic Transaction 1'], type:[ 'Cancelled'],},
    {date_id: 1, title: ['Premium Transaction 1'], type:[ 'Pending'],},
    {date_id: 1, title: ['Freemium Transaction 1'], type:[ 'Dispute'],},
    {date_id: 1, title: ['Bronze Transaction 1'], type:[ 'Dispute',] },
    {date_id: 2, title: ['Transaction 2'], type:[ 'Cancelled'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Pending'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Dispute'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Dispute',] },
    {date_id: 2, title: ['Transaction 2'], type:[ 'Cancelled'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Pending'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Dispute'],},
    {date_id: 2, title: ['Transaction 2'], type:[ 'Dispute',] },
    {date_id: 3, title: ['Transaction 3'], type:[ 'Cancelled'],},
    {date_id: 3, title: ['Transaction 3'], type:[ 'Pending'],},
    {date_id: 3, title: ['Transaction 3'], type:[ 'Dispute'],},
    {date_id: 3, title: ['Transaction 3'], type:[ 'Dispute',] },
    {date_id: 3, title: ['Transaction 3'], type:[ 'Cancelled'],},
    {date_id: 3, title: ['Transaction 3'], type:[ 'Pending'],},
    {date_id: 3, title: ['Transaction 3'], type:[ 'Dispute'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Pending'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Dispute'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Dispute',] },
    {date_id: 4, title: ['Transaction 4'], type:[ 'Cancelled'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Pending'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Dispute'],},
    {date_id: 4, title: ['Transaction 4'], type:[ 'Dispute'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Dispute'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Cancelled'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Pending'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Dispute'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Dispute',] },
    {date_id: 5, title: ['Transaction 5'], type:[ 'Cancelled'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Pending'],},
    {date_id: 5, title: ['Transaction 5'], type:[ 'Dispute'],},
    { date_id: 5, title: ['Transaction 5'], type:[ 'Dispute',] },
    { date_id: 5, title: ['Transaction 5'], type:[ 'Cancelled',] },
  ]
}